### PR TITLE
Rephraser

### PR DESCRIPTION
**Pull request by spammenotinoz**

### CODE REVIEW

**Comment by fkesheh** [comment]
There are some coding issues and you are missing the db types

[diff.txt](https://github.com/spammenotinoz/chatbot-ui/files/14606073/diff.txt)

**Comment by fkesheh** [comment]
Run `npm run db-types` and commit the changes

app/[locale]/login/page.tsx
```
     if (!homeWorkspace) {
-      throw new Error(error.message)
+      throw new Error(error?.message)
     }
```

**Comment by spammenotinoz** [comment]
> There are some coding issues and you are missing the db types
> 
> [diff.txt](https://github.com/spammenotinoz/chatbot-ui/files/14606073/diff.txt)

Thank-you was not aware if of the dbtypes.  You can ignore the DIFF, as I was testing with the official codebase, that code is my PlayGround.  I can't code, so just messing around. 
When tested, the only code change from Mckay was the addition of this line in route.ts, so I can have visability of what was calls are made to OpenAI in real-time. (Yes should have used a system variable, I realise that now)
baseURL: "https://gateway.ai.cloudflare.com/v1/....."
baseURL: "https://gateway.ai.cloudflare.com/v1/a03197fe72510387a4b4e9f7f3595e47/open-ai/openai"

**Comment by spammenotinoz** [comment]
Sorry, I made an incorrect assumption that it was not working as I was not seeing the hits on the API Gateway, when perhaps it is because when I check the Vercel logs, indeed I see entries from the Rephraser.

I had this line added to my openai/route.ts
 baseURL: "https://gateway.ai.cloudflare.com/v1/a03197fe72510387a4b4e9f7f3595e47/open-ai/openai"
But I failed to add to the retrievers.  That is now fixed and I can see the calls to GPT-3.5-turbo when using the GPT-4 model.

Please accept my apologies for wasting your time, you have been very helpful.
image

PS: The network connection lost are new errors.  Will keep an eye on things, but appears unrelated.

**Pull request merged**
